apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-k8s-ingress-controller
spec:
  selector:
    matchLabels:
      app: cic-k8s-ingress-controller
  replicas: 1
  template:
    metadata:
      name: cic-k8s-ingress-controller
      labels:
        app: cic-k8s-ingress-controller
      annotations:
    spec: 
      serviceAccountName: cic-k8s-role
      containers:
      - name: cic-k8s-ingress-controller
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.7.6"
        env:
        # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled) 
         - name: "NS_IP"
           value: "172.16.16.74"
         # Set username for Nitro
         - name: "NS_USER"
           value: "nsroot"
         # Set user password for Nitro
         - name: "NS_PASSWORD"
           value: "nsroot"
         # Set log level
         - name: "EULA"
           value: "yes"
        args:
          - --ingress-classes
            vpx
          - --feature-node-watch
            false
        imagePullPolicy: Always